addons:
  apt:
    packages:
      - lynx
language: java
sudo: false
 notifications:
    slack: countrykirudiha:ONz5m2hUKvyiMDwohYmOfEi2


after_success:
      - if [ -f /home/travis/build/kirudiha/country-springboot-ajax/app/build/outputs/lint-results-debug.html ]; then lynx -dump /home/travis/build/kirudiha/country-springboot-ajax/app/build/outputs/lint-results-debug.html; fi

   
