addons:
  apt:
    packages:
      - lynx
language: java
sudo: false
script: mvn clean -Dtest=StudentControllerTest3 test && mvn surefire-report:report
notifications:

    slack: countrykirudiha:8UbnwbsvzlCIlXXoxZ6ZPNiu
    on_success: always

    on_failure: always # default: always

after_success:
      - if [ -f /home/travis/build/kirudiha/country-springboot-ajax/app/build/outputs/lint-results-debug.html ]; then lynx -dump /home/travis/build/kirudiha/country-springboot-ajax/app/build/outputs/lint-results-debug.html; fi

   